//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeasurementsModule.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeasurementsModule.Strings.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string BtnStart {
            get {
                return ResourceManager.GetString("BtnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string BtnStop {
            get {
                return ResourceManager.GetString("BtnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanal.
        /// </summary>
        internal static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern der Konfiguration abgebrochen..
        /// </summary>
        internal static string ConfigurationAbborted {
            get {
                return ResourceManager.GetString("ConfigurationAbborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration erfolgreich geladen..
        /// </summary>
        internal static string ConfigurationLoadedSuccessfully {
            get {
                return ResourceManager.GetString("ConfigurationLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration konnte nicht geladen werden..
        /// </summary>
        internal static string ConfigurationNotLoadable {
            get {
                return ResourceManager.GetString("ConfigurationNotLoadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration konnte nicht gespeichert werden..
        /// </summary>
        internal static string ConfigurationNotSaveable {
            get {
                return ResourceManager.GetString("ConfigurationNotSaveable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration gelöscht..
        /// </summary>
        internal static string ConfigurationRemoved {
            get {
                return ResourceManager.GetString("ConfigurationRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration erfolgreich gespeichert..
        /// </summary>
        internal static string ConfigurationSavedSuccessfully {
            get {
                return ResourceManager.GetString("ConfigurationSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        internal static string CSV_APPEND_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("CSV_APPEND_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte eine Datei auswählen in die die Messwerte gespeichert werden sollen..
        /// </summary>
        internal static string CSV_FILE_DIALOG_PROMPT {
            get {
                return ResourceManager.GetString("CSV_FILE_DIALOG_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Datei auswählen.
        /// </summary>
        internal static string CSV_FILE_DIALOG_TITLE {
            get {
                return ResourceManager.GetString("CSV_FILE_DIALOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überschreiben.
        /// </summary>
        internal static string CSV_OVERWRITE_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("CSV_OVERWRITE_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei bereits vorhanden!.
        /// </summary>
        internal static string CSV_OVERWRITE_MESSAGEBOX_CAPTION {
            get {
                return ResourceManager.GetString("CSV_OVERWRITE_MESSAGEBOX_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Datei ist bereits vorhanden. Die Daten können überschrieben oder hinzugefügt werden..
        /// </summary>
        internal static string CSV_OVERWRITE_MESSAGEBOX_TEXT {
            get {
                return ResourceManager.GetString("CSV_OVERWRITE_MESSAGEBOX_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Lesen der Messwerte..
        /// </summary>
        internal static string ErrorReadingMeasurements {
            get {
                return ResourceManager.GetString("ErrorReadingMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade verfügbare Messwerte..
        /// </summary>
        internal static string LoadAvailableMeasurements {
            get {
                return ResourceManager.GetString("LoadAvailableMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messwert konnte nicht geladen werden..
        /// </summary>
        internal static string MeasurementNotLoadable {
            get {
                return ResourceManager.GetString("MeasurementNotLoadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zyklisches Auslesen der Messwertblöcke wurde gestoppt, weil keine Antwort erfolgte. Möglicherweise wurde die Fahrzeugverbindung verloren..
        /// </summary>
        internal static string MeasurementsReadingConnectionLost {
            get {
                return ResourceManager.GetString("MeasurementsReadingConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zyklisches Auslesen der Messwertblöcke gestartet..
        /// </summary>
        internal static string MeasurementsReadingStarted {
            get {
                return ResourceManager.GetString("MeasurementsReadingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zyklisches Auslesen der Messwertblöcke gestoppt..
        /// </summary>
        internal static string MeasurementsReadingStopped {
            get {
                return ResourceManager.GetString("MeasurementsReadingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Messwert vorhanden..
        /// </summary>
        internal static string NoMeasurementAvailable {
            get {
                return ResourceManager.GetString("NoMeasurementAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnoseprotokoll wird nicht unterstützt..
        /// </summary>
        internal static string ProtocolIsNotSupported {
            get {
                return ResourceManager.GetString("ProtocolIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lese Messwert.
        /// </summary>
        internal static string ReadMeasurement {
            get {
                return ResourceManager.GetString("ReadMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertig..
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
    }
}
