'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18047
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Resources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
    '''</summary>
    Friend Shared ReadOnly Property AppIcon() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("AppIcon", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Below is the Customer object loaded twice in two separate Units of Work..
    '''</summary>
    Friend Shared ReadOnly Property ModifiedPropertiesMessagesN1() As String
        Get
            Return ResourceManager.GetString("ModifiedPropertiesMessagesN1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The ‘CompanyName’ property value is modified in the first Unit of Work and the ‘Phone’ – in the second..
    '''</summary>
    Friend Shared ReadOnly Property ModifiedPropertiesMessagesN2() As String
        Get
            Return ResourceManager.GetString("ModifiedPropertiesMessagesN2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The second Unit of Work is committed to the database. In the first Unit of Work, Customer is reloaded with merging its current changes with changes from the database. As the result, the &apos;Phone&apos; property values are the same in both Units of Work..
    '''</summary>
    Friend Shared ReadOnly Property ModifiedPropertiesMessagesN3() As String
        Get
            Return ResourceManager.GetString("ModifiedPropertiesMessagesN3", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The &apos;CompanyName&apos; property value is modified in both Units of Work..
    '''</summary>
    Friend Shared ReadOnly Property ModifiedPropertiesMessagesN4() As String
        Get
            Return ResourceManager.GetString("ModifiedPropertiesMessagesN4", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The changes in the second Unit of Work are committed to the database. The LockingException is thrown when the Customer reload occurs in the first Unit of Work, because of the merge collision..
    '''</summary>
    Friend Shared ReadOnly Property ModifiedPropertiesMessagesN5() As String
        Get
            Return ResourceManager.GetString("ModifiedPropertiesMessagesN5", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The modified property value is reset and the Customer is successfully reloaded in the first Unit of Work..
    '''</summary>
    Friend Shared ReadOnly Property ModifiedPropertiesMessagesN6() As String
        Get
            Return ResourceManager.GetString("ModifiedPropertiesMessagesN6", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property ShowCode_32x32() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ShowCode_32x32", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Wizard_16x16() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Wizard_16x16", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Wizard_32x32() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Wizard_32x32", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Xpo_LargeIcon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Xpo_LargeIcon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Class
