//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialTools.ProductionModeService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpecialTools.ProductionModeService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivierung des Produktionsmodus abgeschlossen!.
        /// </summary>
        internal static string ACTION_INFO_ACTIVATED {
            get {
                return ResourceManager.GetString("ACTION_INFO_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktionsmodus wird aktiviert!.
        /// </summary>
        internal static string ACTION_INFO_ACTIVATING {
            get {
                return ResourceManager.GetString("ACTION_INFO_ACTIVATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivierung des Produktionsmodus abgeschlossen!.
        /// </summary>
        internal static string ACTION_INFO_DEACTIVATED {
            get {
                return ResourceManager.GetString("ACTION_INFO_DEACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktionsmodus wird deaktiviert!.
        /// </summary>
        internal static string ACTION_INFO_DEACTIVATING {
            get {
                return ResourceManager.GetString("ACTION_INFO_DEACTIVATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} konnte nicht gesetzt werden. Grund: {1}.
        /// </summary>
        internal static string ACTION_INFO_ECU_FAIL {
            get {
                return ResourceManager.GetString("ACTION_INFO_ECU_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} befindet sich nun im Zustand {1}.
        /// </summary>
        internal static string ACTION_INFO_ECU_IN_STATE {
            get {
                return ResourceManager.GetString("ACTION_INFO_ECU_IN_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktionsmodus von {0} wird auf {1} gesetzt....
        /// </summary>
        internal static string ACTION_INFO_ECU_MODIFICATION_STARTED {
            get {
                return ResourceManager.GetString("ACTION_INFO_ECU_MODIFICATION_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktionsmodus wird gelesen!.
        /// </summary>
        internal static string ACTION_INFO_READING {
            get {
                return ResourceManager.GetString("ACTION_INFO_READING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktionsmodus wurde ausgelesen!.
        /// </summary>
        internal static string ACTION_INFO_READING_COMPLETE {
            get {
                return ResourceManager.GetString("ACTION_INFO_READING_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktionsmodus wird für {0} Steuergeräte gesetzt.
        /// </summary>
        internal static string ACTION_INFO_SETTING_FOR_X_ECUS {
            get {
                return ResourceManager.GetString("ACTION_INFO_SETTING_FOR_X_ECUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ist nun auf den Produktionsmodus-Master konfiguriert und wartet auf die Umschaltung.
        /// </summary>
        internal static string ACTION_INFO_WAITING_FOR_MASTER {
            get {
                return ResourceManager.GetString("ACTION_INFO_WAITING_FOR_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivieren.
        /// </summary>
        internal static string ACTIVATE {
            get {
                return ResourceManager.GetString("ACTIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivieren.
        /// </summary>
        internal static string ACTIVATING {
            get {
                return ResourceManager.GetString("ACTIVATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfen.
        /// </summary>
        internal static string CHECK {
            get {
                return ResourceManager.GetString("CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfung.
        /// </summary>
        internal static string CHECKING {
            get {
                return ResourceManager.GetString("CHECKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte keine Verbindung zum Gateway hergestellt werden.
        /// </summary>
        internal static string COULD_NOT_CONNECT_TO_GATEWAY {
            get {
                return ResourceManager.GetString("COULD_NOT_CONNECT_TO_GATEWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivieren.
        /// </summary>
        internal static string DEACTIVATE {
            get {
                return ResourceManager.GetString("DEACTIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivieren.
        /// </summary>
        internal static string DEACTIVATING {
            get {
                return ResourceManager.GetString("DEACTIVATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauptgruppe.
        /// </summary>
        internal static string LOCALIZED_GROUP_NAME {
            get {
                return ResourceManager.GetString("LOCALIZED_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool zum Lesen und Setzen des Produktionsmodus.
        /// </summary>
        internal static string LOCALIZED_TOOL_DESCRIPTION {
            get {
                return ResourceManager.GetString("LOCALIZED_TOOL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktionsmodus.
        /// </summary>
        internal static string LOCALIZED_TOOL_NAME {
            get {
                return ResourceManager.GetString("LOCALIZED_TOOL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt ist nicht gesetzt!.
        /// </summary>
        internal static string NO_PROJECT {
            get {
                return ResourceManager.GetString("NO_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Projekt.
        /// </summary>
        internal static string NO_PROJECT_ERROR_MSG {
            get {
                return ResourceManager.GetString("NO_PROJECT_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein P-Mode ECU vorhanden.
        /// </summary>
        internal static string PRODUCTION_MODE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("PRODUCTION_MODE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap productionMode_png {
            get {
                object obj = ResourceManager.GetObject("productionMode.png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] productionMode_svg {
            get {
                object obj = ResourceManager.GetObject("productionMode.svg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Zurücksetzen.
        /// </summary>
        internal static string RESET_LOG {
            get {
                return ResourceManager.GetString("RESET_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zugriff verweigert.
        /// </summary>
        internal static string RESULT_ACCESS_DENIED {
            get {
                return ResourceManager.GetString("RESULT_ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anpassung nicht verfügbar.
        /// </summary>
        internal static string RESULT_ADAPTATION_MISSING {
            get {
                return ResourceManager.GetString("RESULT_ADAPTATION_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schreiben der Anpassung fehlgeschlagen.
        /// </summary>
        internal static string RESULT_ADAPTATION_WRITE_FAILED {
            get {
                return ResourceManager.GetString("RESULT_ADAPTATION_WRITE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlercode beim Schreiben der Anpassung.
        /// </summary>
        internal static string RESULT_ADAPTATION_WRITE_NRC {
            get {
                return ResourceManager.GetString("RESULT_ADAPTATION_WRITE_NRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung fehlgeschlagen.
        /// </summary>
        internal static string RESULT_CONNECTION_FAILED {
            get {
                return ResourceManager.GetString("RESULT_CONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schreiben eines konfigurierten Services fehlgeschlagen.
        /// </summary>
        internal static string RESULT_CUSTOM_HEX_SERVICE_DISPATCH_FAILED {
            get {
                return ResourceManager.GetString("RESULT_CUSTOM_HEX_SERVICE_DISPATCH_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlercode beim Schreiben eines konfigurierten Services.
        /// </summary>
        internal static string RESULT_CUSTOM_HEX_SERVICE_NRC {
            get {
                return ResourceManager.GetString("RESULT_CUSTOM_HEX_SERVICE_NRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic Task konnte nicht erstellt werden.
        /// </summary>
        internal static string RESULT_DIAGNOSTIC_TASK_CREATION_FAILED {
            get {
                return ResourceManager.GetString("RESULT_DIAGNOSTIC_TASK_CREATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string RESULT_ERROR {
            get {
                return ResourceManager.GetString("RESULT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige PIN.
        /// </summary>
        internal static string RESULT_INVALID_PIN {
            get {
                return ResourceManager.GetString("RESULT_INVALID_PIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messwertblock nicht verfügbar.
        /// </summary>
        internal static string RESULT_MEASUREMENT_BLOCK_MISSING {
            get {
                return ResourceManager.GetString("RESULT_MEASUREMENT_BLOCK_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Fehler.
        /// </summary>
        internal static string RESULT_NO_ERROR {
            get {
                return ResourceManager.GetString("RESULT_NO_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktionsmodus Master konnte nicht gesetzt werden.
        /// </summary>
        internal static string RESULT_PMODE_MASTER_NOT_SET {
            get {
                return ResourceManager.GetString("RESULT_PMODE_MASTER_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Neustart.
        /// </summary>
        internal static string RESULT_RESTART_FAILED {
            get {
                return ResourceManager.GetString("RESULT_RESTART_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessionwechsel fehlgeschlagen.
        /// </summary>
        internal static string RESULT_SESSION_CHANGE_FAILED {
            get {
                return ResourceManager.GetString("RESULT_SESSION_CHANGE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zustand hat sich nicht verändert.
        /// </summary>
        internal static string RESULT_STATE_DID_NOT_CHANGE {
            get {
                return ResourceManager.GetString("RESULT_STATE_DID_NOT_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string RESULT_SUCCESS {
            get {
                return ResourceManager.GetString("RESULT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannter Fehler.
        /// </summary>
        internal static string RESULT_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("RESULT_UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergebnisse.
        /// </summary>
        internal static string RESULTS {
            get {
                return ResourceManager.GetString("RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiv.
        /// </summary>
        internal static string STATE_ACTIVE {
            get {
                return ResourceManager.GetString("STATE_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inaktiv.
        /// </summary>
        internal static string STATE_INACTIVE {
            get {
                return ResourceManager.GetString("STATE_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannt.
        /// </summary>
        internal static string STATE_UNKNOWN {
            get {
                return ResourceManager.GetString("STATE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erwartet Master Switch....
        /// </summary>
        internal static string STATE_WAITING_FOR_MASTER {
            get {
                return ResourceManager.GetString("STATE_WAITING_FOR_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductionModeService.
        /// </summary>
        internal static string TOOL_NAME {
            get {
                return ResourceManager.GetString("TOOL_NAME", resourceCulture);
            }
        }
    }
}
